# Generated by Django 5.2 on 2025-05-30 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypeer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='title',
            field=models.CharField(default='Untitled Group', max_length=100, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, max_length=255, verbose_name='interests'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studypeer.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
