# Generated by Django 5.2 on 2025-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypeer', '0002_remove_studygroup_name_remove_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='meeting_times',
            field=models.DateTimeField(),
        ),
    ]
